name = "tsuki-cms-v2"
pages_build_output_dir = "out"

# Environment variables - declared here but values come from:
# 1. Cloudflare Pages Dashboard settings (for deployments)  
# 2. .dev.vars file (for local development only)
[env.production.vars]
NEXT_PUBLIC_SUPABASE_URL = ""
NEXT_PUBLIC_SUPABASE_ANON_KEY = ""

[env.preview.vars] 
NEXT_PUBLIC_SUPABASE_URL = ""
NEXT_PUBLIC_SUPABASE_ANON_KEY = ""

compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"] 