name = "tsuki-cms-v2"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[build]
command = "npm run build"

[build.environment]
NODE_VERSION = "20" 