name = "tsuki-cms-v2"
pages_build_output_dir = "out"

compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Environment variables injected during build
[vars]
NODE_VERSION = "20"
NEXT_PUBLIC_SUPABASE_URL = ""
NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
