name = "tsuki-cms-v2"
pages_build_output_dir = ".vercel/output/static"

compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Environment variables injected during build
[vars]
NODE_VERSION = "20"

