name = "tsuki-cms-v2"
pages_build_output_dir = ".next"

# Environment variables are now set only in Cloudflare Pages Dashboard
# and .dev.vars file (local development only)
[vars]
NODE_VERSION = "20"

compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"] 